### ISSUE TITLE
0x5b - balance between security and testability

### ISSUE THREAD

**Issue by romualdszkudlarek** [OWASP/owasp-mstg#104]
The beginning of "Setting Up Your Testing Environment" / "Preparation" is great, but in my mind puts too much emphasis on the fact a good level of security may render security testing tedious. While this is true, maybe a more balanced message could be given, as the guide should not provide reasons to lessen the security level provided to an app (unfortunately, too often people take advantage of bad reasons to forget implementing security...). 

Maybe, as stated later in the chapter, better say that the testing team should work with developers to get a dedicated version of the app where some controls are not implemented or may be bypassed more easily (or, in the same way, work with the IT team to get a dedicated testing network, or any other solution for a testing environnement).

**Comment by sushi2k** [comment]
Hi @romualdszkudlarek. Thanks for all your feedback. Makes sense. Just added "Either way, the testing team responsible for the Android assesment need to work together with the App developer(s) and operation team in order to find a proper solution for a working testing environment."

What do you think?

https://github.com/OWASP/owasp-mstg/commit/4f7cbd82da51c57324e6412dc7d5d30e5ce04121

**Comment by romualdszkudlarek** [comment]
Fine for me :-)
