### ISSUE TITLE
The type of CC license is inconsistent between documents.

### ISSUE THREAD

**Issue by coky-t** [OWASP/owasp-mstg#1060]
It is described as CC BY-SA 3.0 in README.md and LICENSE file.
But in the text of 0x02-Frontispiece.md it is described as CC BY-SA 4.0 .
And in the image of 0x02-Frontispiece.md it is described as CC BY-NC-SA .

Which is BY-SA or BY-NC-SA correct ? What is the version number of CC ?

**Comment by sushi2k** [comment]
Thanks for pointing out this inconsistency @coky-t!

i just found that version 4.0 of CC is already out since 2013 https://creativecommons.org/share-your-work/licensing-considerations/version4/. It seems the intention of it is to have a more international focus compared to 3.0 that seems to have a more US focus. I am not a lawyer and have that in-depth knowledge about open source licenses, but I guess I will just make it CC 4.0 for now, as also OWASP is listing it as one of it's licenses. 

Do you have any suggestions or know if 3.0 or 4.0 does make more sense for an internaltional documentation project? It seems 4.0 should be the way to go.

**Comment by coky-t** [comment]
I appreciate your research and consideration.
I have no objection to adopt 4.0 as well.

**Comment by commjoen** [comment]
@coky-t & @sushi2k: looks like this can be closed...

**Comment by commjoen** [comment]
Ah.. the masvs it's frontispiece is not done yet... then we're complete

**Comment by coky-t** [comment]
I have found another mistake.
The license image file has a .png extension, but since mstg's frontispiece is described as .jpg, the image is not displayed.
