### ISSUE TITLE
New Encyrption Method called Adiantum 

### ISSUE THREAD

**Issue by sushi2k** [OWASP/owasp-mstg#1135]
**Platform:**
Android 

**Description:**
New encryption method introduced with Android P called Adiantum for CPUs that lack support of AES:
https://source.android.com/security/encryption/adiantum
https://security.googleblog.com/2019/02/introducing-adiantum-encryption-for.html
https://tosc.iacr.org/index.php/ToSC/article/view/7360

**Comment by joscandreu** [comment]
I'd like to contribute on this topic. However I think that an in-depth review of Adiantum would not fit in the scope of mstg, since all the available information seems to be focused on implementing it on the Android platform, which is a task to be done by vendors or at most by ROM hackers given that it implies applying patches to the kernel and to AOSP images and recompiling them.
I propose to write a light review of the algorithm and the reason of its existence. Sounds right?

**Comment by commjoen** [comment]
I would say: let's try to indeed keep it in the context of the android platform: e.g.: where/when do you use it and what parameters should you look for?

**Comment by commjoen** [comment]
@joscandreu : I have sent you a github invite so we can assign this issue to you :)

**Comment by joscandreu** [comment]
Invitation accepted :)

**Comment by commjoen** [comment]
Thanks! Issue assigned :)

**Comment by joscandreu** [comment]
I created a PR so you can give opinion on what I have written so far. It is still WIP.
I added two sub-sections for file-based encryption and for full-disk encryption which I intend to complete ASAP.
I thought it made sense to write all this inside the Android platform overview chapter.

Waiting to hear your thoughts!

**Comment by commjoen** [comment]
Fixed in #1342. Thanks @joscandreu !
