### ISSUE TITLE
6c - Create Binary Analysis

### ISSUE THREAD

**Issue by cpholguera** [OWASP/owasp-mstg#1374]
add "#### Binary Analysis" to "### Dynamic Analysis" before "### Tampering and Runtime Instrumentation"

```
#### Binary Analysis
##### Symbolic Execution
```

Check chapter 5c to keep it consistent.

**Comment by su-vikas** [comment]
I will take up this one. 
In android bernhard used angr, i dont use angr much, i use miasm, is that something okay? Or for consistency we stick with angr? I think it should be not much time consuming to use angr on a simple app. Let me know.

**Comment by su-vikas** [comment]
can we include use of code emulation using unicorn in this section?

**Comment by cpholguera** [comment]
Hi @su-vikas , that sounds very nice. If you would like to describe the three methods we're open to that. I think miasm is also a very nice option to consider, also angr would be nice to have so we can show a use case on both Android and iOS. Same goes for code emulation :+1: thanks!

**Comment by su-vikas** [comment]
Perfect. I will get started with this one. You can put hacktoberfest tag, as I intent to do it in october :P.

**Comment by cpholguera** [comment]
Done! Thanks @su-vikas , looking forward to it :)

**Comment by cpholguera** [comment]
Hi @su-vikas , any news on this issue? Thanks!

**Comment by su-vikas** [comment]
Hi @cpholguera, things are moving fine. I have got angr working to solve uncrackable level1. Just looking in more details of angr, so that i can explain the script in simple words. 

The solution is not purely symbolic, it is using angr's concrete execution engine, but nevertheless should be a good example to have. Which makes me unsure to put this content in "symbolic execution" heading, we can discuss this once I send the PR. Let me know if you think otherwise. 

Using miasm is cumbersome for mach-o files. Miasm doesn't have a mach-o loader, there is a still a way to use it, but it is not that straightforward, so decided against using it.

**Comment by cpholguera** [comment]
Hi @su-vikas , that sounds very nice. You can gladly put it in the section and if it doesn't completely fit we can think of where to shift it once the PR is opened.

Regarding miasm, if you have a nice, easy and  almost self-explanatory example that would be worth of including it into the Android chapter, please do so. We could set up a separate issue for that.

Thanks for the quick feedback :)

**Comment by commjoen** [comment]
Fixed in #1521 . Thanks @su-vikas !
