### ISSUE TITLE
Update Android Basic Security Testing to Include Inspeckage Usage

### ISSUE THREAD

**Issue by J3rry367** [OWASP/owasp-mstg#1445]
Inspeckage is referenced a couple of times within the MSTG, but it'd be nice if there was more of an explanation of it's use case in the Android Basic Security Testing section.

I've found that It's extremely useful in the initial information gathering stages as it allows you to download the APK, explore the data directory, package information, shared_prefs, etc. 

On top of that, when it is referenced for use, in one of the later sections, it is most helpful if it has been inspecting the app as the application functionality is being explored rather than starting it up when moving into the later testing and then re-visiting all of the app functionality.

**Comment by commjoen** [comment]
Hi @J3rry367! Thank you for submitting this issue. We used to have Inspeckage more described in the MSTG, but due to the work necessary to install it and the issues there have been on various android versions (Both due the Xposed components which have not always been working on each android verison), we removed it.
However, I do believe there is space in the host computer tools section at https://github.com/OWASP/owasp-mstg/blob/master/Document/0x05b-Basic-Security_Testing.md#recommended-tools---host-computer . Would you mind to create a small introduction on Inspeckage and refer then to its readme for further installation?

**Comment by J3rry367** [comment]
yep I can put something together

**Comment by commjoen** [comment]
Great! Looking forward to it!

**Comment by cpholguera** [comment]
Closed after long inactivity. Please re-open if you've something new :)
