### ISSUE TITLE
Translation for Chinese Language Version

### ISSUE THREAD

**Issue by boblone19** [OWASP/owasp-mstg#1588]
**Describe the issue**
Missing Chinese Language, I want create PR to do the translation for Chinese version of mstg thx

**Comment by sushi2k** [comment]
Hi @boblone19. Thanks for reaching out to us.
The MSTG project is an extensive book (over 500 pages) that is ever-changing. We are changing the content almost on a daily basis. We also have many tickets/Github issues due to all the changes on Android and iOS from the new major versions (iOS 12/13 and Android 9/10) that would need to be worked on and incorporated into the MSTG.

Because of this, we are not encouraging at the moment the translation of the MSTG into other languages. If you want to help on the tickets we have at the moment (https://github.com/OWASP/owasp-mstg/issues) please feel free to reach out to me in our OWASP Slack channel https://github.com/OWASP/owasp-mstg/#contributions-feature-requests-and-feedback

**Comment by sushi2k** [comment]
If you are keen in translating the MASVS would make more sense, as this document is more stable and will change only a few times a year https://github.com/OWASP/owasp-masvs. Therefore it's easier to manage the changes.

We already have a translation into traditional Chinese, but not simplified Chinese. 

I will close this ticket, but feel free to reach out to me via Slack if you are interested in the MSTG issues or the MASVS translation into simpliefied Chinese.

**Comment by boblone19** [comment]
Whatever u said is right, i will keep doing my simplified Chinese MSTG, about 500 pages that u mention? i have finished almost 50% with in 3days, in the future if u guys want a simplified Chinese MSTG, feel free to come https://github.com/boblone19/owasp-mstg
