### ISSUE TITLE
Referencing David Thiel's book Syntax Error

### ISSUE THREAD

**Issue by iambrosie** [OWASP/owasp-mstg#1637]
On https://github.com/OWASP/owasp-mstg/blob/master/Document/0x06h-Testing-Platform-Interaction.md#testing-ios-webviews-mstg-platform-5, David Thiel, iOS Application Security: The Definitive Guide for Hackers and Developers (Kindle Locations 3394-3399), No Starch Press, Kindle Edition is listed under the References section.

None of the references to the book seem to work throughout the document, i.e. they are rendered as [#thiel2].

**Comment by cpholguera** [comment]
Hi @iambrosie,  in this case that's according to our style guide:

https://github.com/OWASP/owasp-mstg/blob/master/style_guide.md#books-and-papers

Anyway, thanks for keeping an eye on potential syntax errors :)

**Comment by lwierzbicki** [comment]
As a matter of fact I added this reference, so we can be compliant with our style-guide. Additionally there is a reference to other David Thiel's book (in 0x06h-Testing-Platform-Interaction.md), that's why I added 2 to make it unique ;)

**Comment by iambrosie** [comment]
Hi @cpholguera,

What I understand from the style guide that was shared is that if we renamed 

> [#thiel2]
to
> [thiel2]

in https://github.com/OWASP/owasp-mstg/blob/master/Document/0x06h-Testing-Platform-Interaction.md#references all should be good, i.e. "This could lead to a URL scheme hijacking attack (see page 136 in [#thiel2])" will be rendered correctly.

Correct?

**Comment by cpholguera** [comment]
Hi @iambrosie , maybe the confusion comes from the notation itself. This notation is not markdown, no links will be rendered. It's simply a plain/raw way to include references to books within the text that can be then found in the references section. Therefore, it's actually fine as it is and as described in the style guide.

Anyway, thank you very much for rising the issue, it's nice to know that you're also keeping an eye on this kind of details :)

I hope this helps clarifying the situation so I'll close the issue. Please let me know otherwise.
