### ISSUE TITLE
Content Needs To Be More Descriptive

### ISSUE THREAD

**Issue by shivsahni** [OWASP/owasp-mstg#1673]
The following section is taken from here: https://mobile-security.gitbook.io/mobile-security-testing-guide/ios-testing-guide/0x06f-testing-local-authentication

> Please be aware that using either the LocalAuthentication.framework or the Security.framework, will be a control that can be bypassed by an attacker as it does only return a boolean and no data to proceed with. See Don't touch me that way, by David Lindner et al for more details. 

It says Security.framework can be bypassed too as it only returns the boolean value but the actual component of Security.framework i.e. Keychain services seems to be robust from such attacks since the authentication is protected through cryptographic primitive. In case it is actually vulnerable can we elaborate it further?

**Comment by cpholguera** [comment]
Hi @shivsahni, it would be great if we could be more precise and elaborate here as you said. Would you like to help us doing that here? It'd help us a lot if you'd open a PR with your suggestions :)

**Comment by shivsahni** [comment]
Hey @cpholguera,

Just like the previous issue: 

I can definitely open a PR for this, not an issue at all. However, could you please confirm if whatever I mentioned makes sense and we actually need to correct the content.

**Comment by sushi2k** [comment]
Hi @shivsahni. I guess the point is that you can also hook into low-level functions and overwrite the return values. At the end of the day LAContext is an abstraction or high level function that is relying on the Security Framework (low level C-API). 
That's why the best practice is to encrypt some information via keychain services that can only be decrypted after successful biometric authentication which happens in the secure enclave. The verification in the SE cannot be hooked, even on a jailbroken device.
Hope that makes sense.

**Comment by cpholguera** [comment]
Closing after long inactivity, please re-open if it needs more clarification or contact us on Slack :)
