### ISSUE TITLE
[iOS] Anti-Reversing Defenses, File Integrity Checks - application source code integrity checks issues

### ISSUE THREAD

**Issue by teok0045** [OWASP/owasp-mstg#1694]
Hi,
 
i was actually trying to implement Application source code integrity checks to verify if the IPA file is not being tampered with during runtime.

I have tried integrating the file integrity check code provided by this article(https://mobile-security.gitbook.io/mobile-security-testing-guide/ios-testing-guide/0x06j-testing-resiliency-against-reverse-engineering#file-integrity-checks-mstg-resilience-3-and-mstg-resilience-11).

However, the condition at the line "`if (cmd->cmd == LC_SEGMENT) `" has never been met and it will keep looping at run-time.

We tried to print out the value of cmd and the value was 0 throughout the whole process, while the expected LC_SEGMENT is not 0.

We have done quite a few of research and testing but the result is still not meet the expectation.

Would like to seek some help from you guys, thank you!

**Comment by cpholguera** [comment]
Hi @teok0045, it seems that the source code is very old (2013). Probably originating here:

https://www.fabernovel.com/en/insights/tech-en/securing-ios-apps-patching-binaries

As a quick response I could tell you if you've tried with LC_SEGMENT_64 as I guess that you're testing on a modern device.

Anyway thanks for raising the question, we'll address this issue.

**Comment by teok0045** [comment]
Hi @cpholguera ,

Am glad that finally someone came into looking at the bug.

Thank you for addressing the issue!

**Comment by TommyLeong** [comment]
Hi @cpholguera, assumingly you were looking into the issue raised. Do we have any progress on this? I was as well referring to [article shared earlier](https://mobile-security.gitbook.io/mobile-security-testing-guide/ios-testing-guide/0x06j-testing-resiliency-against-reverse-engineering#file-integrity-checks-mstg-resilience-3-and-mstg-resilience-11) by @teok0045

**Comment by cpholguera** [comment]
Hi @TommyLeong , we've discussed internally regarding this topic and decided that still having this kind of code snippets that are not coming directly from us might be misleading. To save trouble we'll be cleaning up the guide, i.e. we will remove them. For us it's not plausible to maintain 3rd party code bases but we will keep providing the community with the valuable information that you can find in the MSTG so that you then learn how to deal with these things on your own. We hope you can understand our position here, thanks for asking and have a nice weekend!
