### ISSUE TITLE
Android KeyStore Should Belong to the Overview Section

### ISSUE THREAD

**Issue by ThunderSon** [OWASP/owasp-mstg#1771]
**Describe the issue**
[Android KeyStore](https://mobile-security.gitbook.io/mobile-security-testing-guide/android-testing-guide/0x05d-testing-data-storage#keystore) is placed in the Static Analysis part, where it discusses how KeyStore works.

It should be part of the Overview section, as it's giving information about the functionality.

**Comment by lwierzbicki** [comment]
I think it is a good point. I redesigned a bit next chapter (testing android crypto), but I put Android Keystore in Testing Data Storage the same way it was before. 

@sushi2k @commjoen - what do you think? Should we change structure in Testing Data Storage the same way as in Testing crypto?

**Comment by lwierzbicki** [comment]
@cpholguera I think it is related to #1631 . Any action, depends on what was agreed.

**Comment by cpholguera** [comment]
Consider removing all descriptions that can be anyway found in Android Docs, and refer by link.

**Comment by cpholguera** [comment]
First of all sorry about the "cryptic" message. After taking another look at the whole thing I will now explain a bit more :)

We see 3 PRs in this Issue, manly because this way we can better follow the changes and can act more quicly. If we open one big PR for this it could take months until we process it :/ 

**First PR**: move the "Android KeyStore" and other sections describing "Data Storage" to the top of the chapter.  If we go though the whole chapter we can find:
  - "Local Storage" incl. Shared prefs, Databases, Internal and external storage, KeyStore.
  - Logs
  - Backups
  - Process Memory

```
## Overview
Intro to Local Storage, including mention of Logs, Backups, Process Memory.

Next, put the most relevant ones" as subsections (those which have big descriptions already).

### Shared Preferences
### Databases
...
###  
```


**Second PR**: Review this new Overview and remove all information that can be already found online. For instance:
The section for "Key Attestation" has a lot of information, most of it addresing the developers. For that there is the official site: 
[Key Attestation](https://developer.android.com/training/articles/security-key-attestation "Key Attestation").  It should be evaluated if we are really providing added value here **for the tester**. If not, it should be enough to read that site.


**Third PR**: Ensure that each Test Case Section has proper short and concise "Overview" telling what we are verifying and not "what Android has". Then, "Static" and "Dynamic analysis" sections should properly tell the tester WHAT TO TEST and how. Because that cannot be found somewhere else. Of course, taking [Key Attestation](https://developer.android.com/training/articles/security-key-attestation "Key Attestation") as a support and maybe some links to examples of code but mostly including our "added value" as Testing Guide.

**Comment by cpholguera** [comment]
Thanks @ThunderSon and @lwierzbicki for raising and giving inputs regarding this issue. Now divided into 3 issues, see above. Please let us know who would like to start and we will assign you to them :)
