### ISSUE TITLE
[Tool] Link to IDB is dead

### ISSUE THREAD

**Issue by righettod** [OWASP/owasp-mstg#1899]
**Platform:**
iOS

**Description:**

The link to IDB homepage  in [this section](https://github.com/OWASP/owasp-mstg/blob/master/Document/0x08-Testing-Tools.md#idb) is dead:

![image](https://user-images.githubusercontent.com/1573775/114978552-a1f79e80-9e89-11eb-847c-498335e866ad.png)

However, the [GitHub repo](https://github.com/dmayer/idb) still exists even if it was not updated since 2017.

Thanks a lot in advance 😃

**Comment by cpholguera** [comment]
hi @righettod, thanks for reporting. Maybe it's actually time to retire IDB since it's pretty old, hasn't been updated and does not really bring added value given the current alternatives. Would you like to help us get rid of it?

https://github.com/OWASP/owasp-mstg/search?q=idb&type=

(excluding of course the CHAGELOG files)

**Comment by righettod** [comment]
Hi, OK i'm on it 😃

**Comment by righettod** [comment]
PR #1900 submitted.
