### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by bimsec** [OWASP/owasp-mstg#2087]
### MSTG Chapter

Cryptography in Mobile Apps

### File Line Number

177

### Context

“Male sure” but should be “Make sure”

**Comment by cpholguera** [comment]
Nicely seen, thanks a lot @bimsec. Would you mind opening a PR including your changes? Please write `Closes #2087` in the description so that it is linked to this issue. Feel free to send any other corrections you may have.

You can simply:

1. Go to the chapter [here](https://github.com/OWASP/owasp-mstg/blob/master/Document/0x04g-Testing-Cryptography.md)

2. Click the edit button
<img width="600" alt="grafik" src="https://user-images.githubusercontent.com/29175115/159294496-4671c2f9-d550-402d-b751-752241f315d4.png">

3. Make the correction

4. Click "Propose Changes" at the bottom of the page.

<img width="600" alt="grafik" src="https://user-images.githubusercontent.com/29175115/159295103-7b65cf43-90ce-4ce2-b0d3-84ac3e86a1ce.png">

**Comment by cpholguera** [comment]
It seems to be fixed now. Thanks @bimsec
