### ISSUE TITLE
0x6b - Author new content on Jailbreaking iOS

### ISSUE THREAD

**Issue by romualdszkudlarek** [OWASP/owasp-mstg#325]
Look for "Jailbreaking the iOS Device"

**Comment by b-mueller** [comment]
Hey @cpholguera, I was hoping that you take over this chapter?

**Comment by cpholguera** [comment]
Sure ;)

El 18 jun. 2017 3:12 p. m., "Bernhard Mueller" <notifications@github.com>
escribió:

Hey @cpholguera <https://github.com/cpholguera>, I was hoping that you take
over this chapter?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/OWASP/owasp-mstg/issues/325#issuecomment-309276920>,
or mute
the thread

**Comment by sushi2k** [comment]
there is already content available in 0x6b. Please have a look at it "Jailbreaking the iOS Device"
