### ISSUE TITLE
0x6h - Author new content on Test Case "Testing Whether JavaScript can access native methods" [iOS]

### ISSUE THREAD

**Issue by romualdszkudlarek** [OWASP/owasp-mstg#380]

**Comment by sushi2k** [comment]
@commjoen Are you working on this now?

**Comment by commjoen** [comment]
No

Sent from a mobile device with autocomplete.

Op 16 jun. 2017 07:10 schreef "Sven" <notifications@github.com>:

@commjoen <https://github.com/commjoen> Are you working on this now?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/OWASP/owasp-mstg/issues/380#issuecomment-308941949>,
or mute
the thread

**Comment by sushi2k** [comment]
@xep624 Can you already share a draft or when do you think it will be ready? Thanks

**Comment by sushi2k** [comment]
This test  case doesn't make much sense for iOS. Closed it. https://github.com/OWASP/owasp-mstg/blob/master/Document/0x06h-Testing-Platform-Interaction.md#testing-whether-java-objects-are-exposed-through-webviews

**Comment by bugwrangler** [comment]
Looks like its "Javascript" not the Java.

**Comment by sushi2k** [comment]
I closed it as there are no Java objects in iOS. But you are right it's about JavaScript accessing functions in iOS, which is of course possible (https://developer.apple.com/library/content/documentation/AppleApplications/Conceptual/SafariJSProgTopics/ObjCFromJavaScript.html). Thanks for your comment. 

The actual problem is, that the MASVS requirement is not generic enough. Will make a PR for it.

**Comment by xep624** [comment]
I'll do this section next week (I'll start on 3rd July)

**Comment by sushi2k** [comment]
Great. Thanks Pawel

**Comment by xep624** [comment]
I see that this point is removed from TO DOs from the file 0x06h-Testing-Platform-Interaction.md. Should I just add it?

**Comment by sushi2k** [comment]
You can add it to "Exposing Native Objects to WebViews"
https://github.com/OWASP/owasp-mstg/blob/master/Document/0x06h-Testing-Platform-Interaction.md#exposing-native-objects-to-webviews
