### ISSUE TITLE
[UNDER REVIEW] 0x5d Data Classification Policy - What is sensitive information?

### ISSUE THREAD

**Issue by sushi2k** [OWASP/owasp-mstg#424]
-- TODO: What is sensitive information? Need to be described, ideally defined by the customer (data classification policy).

**Comment by sushi2k** [comment]
https://github.com/OWASP/owasp-mstg/blob/master/Document/0x04-Testing-Processes-and-Techniques.md#classification-of-data

**Comment by anantshri** [comment]
first 2 paragraph are a bit too dense. (too many words per line), if we can do something about it then it will be good.

**Comment by sushi2k** [comment]
Thanks ananthshri. Just shortened the sentences. Let me know what you think.

**Comment by pmilosev** [comment]
I just read the section and it looks quite OK to me - short and clear.
Just wondering why there is only 'data in transit' and 'data at rest' mentioned.
Shouldn't there also be 'data in use' added to the list ?

**Comment by AlexCline** [comment]
A few suggestions for sensitive information that is commonly used in apps:

- Add 'session tokens' to the list of authentication information. Session tokens are stored in-app rather than credentials, so it's important to protect them on-device since they can be used for session fixation attacks.
- Add 'device identifier' and 'location information' to the list of personally identifiable information. Pending regulations in the EU require that this information be protected, and it's easy to misuse this type of information.
