### ISSUE TITLE
[DISCUSSION] 0x05d Clean state of App

### ISSUE THREAD

**Issue by sushi2k** [OWASP/owasp-mstg#439]
On android, when you app goes in the background, its killed, but the data/state is saved.
Once the user opens the app, you get object called savedInstanceState, which contains the data from the app.
For simplicity lets assume it looks like this:
textInput[username] = random
text[name] = Random
You can, fill the view with the data from the savedInstanceState object, without consulting the server.

-> Should be added to 2.9 Testing for Sensitive Data in Memory. 
Question is if the server should be asking first the server when the app  goes again in the foreground if the session is still valid. If it's not valid delete state. State should then also be deleted after a timeout set on client side.

**Comment by pmilosev** [comment]
On Android, when an app goes in background, it process is suspended, not killed (I believe :)).
So if you send an app in background, without saving your data, and you bring it back to foreground before the system killed the process (e.g. due to lack of resources), your data will still be there (in memory) and the app will work just fine.
The process is killed only if the user explicitly removes all application tasks from recent tasks, or if the system needs the resources.
On the other hand savedInstanceState has a valid use even when the app is actively running in foreground. I.e. When a device configuration changes (e.g. user rotates the device) the Activity is destroyed and re-created from scratch, in which case you need to save / restore your data.

So relying on `onCreate(savedInstanceState)` to check if the session is valid after the app have been in background is probably not what you want.

**Comment by sushi2k** [comment]
@pmilosev Thanks for the input. Do you might want to work on this ticket and create content for it?

**Comment by pmilosev** [comment]
Currently I'm reading trough the existing content and directly editing when I think something can be improved. Then you can cherry pick the modifications you find suitable from my PRs.
I plan to first finish this by the end of next week and then start adding new content.
If no one have started this ticket by then I can take it over.

**Comment by sushi2k** [comment]
Sounds like a plan. Thanks for your support. 👍
