### ISSUE TITLE
Addressing consistency

### ISSUE THREAD

**Issue by pmilosev** [OWASP/owasp-mstg#485]
Once most of the content is authored, someone (probably original authors) need to go trough the whole content and make different wording more consistent.

E.g. different contributors refer to devices differently: device, mobile, phone, tablet, etc.
As both Android and iOS are also used on devices other than mobile phones, the more generic term `device` should be used.

I also noticed different levels of expectations from the reader (different target audience), which should be leveled up.
E.g. Some text refer to advanced techniques like hooking as simple, while others spend several sentences explaining how difficult a test can be due to SSL pinning, or how difficult rooting a device is.

**Comment by b-mueller** [comment]
Great points. I agree that the editing process should be started once most of the content is there, but I think it should be done by a small group of people with good writing skills and perfect English because many of the original authors aren't native speakers. Perhaps we can even hire a professional technical editor if OWASP grants us the funds for that.

We can start with editing though for some chapters, for example the 0x05a-0x05c which is already pretty far developed. We can also continue the discussion about consistency here - I'm off to sleep now though :)
