### ISSUE TITLE
[EDITING] 0x04g, 0x05e, 0x06e Cryptography

### ISSUE THREAD

**Issue by b-mueller** [OWASP/owasp-mstg#507]

**Comment by bolot** [comment]
* Add content to intro
  - Goals of cryptography
  - Overview of types of encryption
    - Symmetric vs asymmetric
    - Uses, secrets
  - Tie cryptographic primitives to the goals they support
  - List the recommended cryptographic algorithms in the beginning, along with the recommended configurations
* Indicate that Data Storage and Networking cover some of the uses of cryptography
  - May not want to store passwords, if possible.
  - iOS: Keychain should be use for storing most sensitive data.
  - On Android, KeyStore
* Delete test cases:
  - Move some of the ECB content to the education section on encryption
  - Data integrity protection - doesn't provide details and some may be covered in networking
* Move the general Cryptography section to the General Testing Guide, instead of the Appendix

**Comment by bolot** [comment]
Need to check:
* Should we remove the Dynamic Analysis sections from this chapter? Most of the analysis currently included is static, requires access to the source code. May not be possible to analyze dynamically.
* What should be covered in the Remediation section? How much detail should be in the Testing Guide vs Developer Guide. Ideally, the Testing Guide would reference best practices in the Developer Guide.
