### ISSUE TITLE
Data Storage on Andorid: Gradle task causes compiler errors

### ISSUE THREAD

**Issue by b-mueller** [OWASP/owasp-mstg#804]
See [feedback on Gitbook](https://www.gitbook.com/book/b-mueller/the-owasp-mobile-security-testing-guide/discussions/7).

"Testing Data Storage on Android" lists a Gradle task which comments out all log statements including any inline string builder. This regex is applied on every release build appending more */*/ with errors at compile time.

**Comment by sushi2k** [comment]
Following scenario:

An error was reported https://www.gitbook.com/book/b-mueller/the-owasp-mobile-security-testing-guide/discussions/7 with the following configuration (which intents to remove all log statements before compiling, see also https://github.com/OWASP/owasp-mstg/blob/master/Document/0x05d-Testing-Data-Storage.md#static-analysis-2):

```
afterEvaluate {
  project.getTasks().findAll { task -> task.name.contains("compile") && task.name.contains("Release")}.each { task ->
      task.dependsOn('removeLogs')
  }

  task removeLogs() {
    doLast {
      fileTree(dir: project.file('src')).each { File file ->
        def out = file.getText("UTF-8").replaceAll("((android\\.util\\.)*Log\\.([ewidv]|wtf)\\s*\\([\\S\\s]*?\\)\\s*;)", "/*\$1*/")
        file.write(out);
      }
    }
  }
}
```

I have added the gradle task in build.gradle and it also shows up in the "other" tasks of the app. 

![image](https://user-images.githubusercontent.com/5951320/48657602-4f261c80-ea6e-11e8-808e-46119b45a0bc.png)

When I am creating a release build, it works without any errors, but the log statements are still there when I decompile the APK.

![image](https://user-images.githubusercontent.com/5951320/48657617-8dbbd700-ea6e-11e8-8b85-4c13cc189e1a.png)

Any idea what is wrong or how to investigate what the problem is? How can I check if the gradle task was executed?

**Comment by commjoen** [comment]
You can use gradle (or the gradlewrapper) from the commandline and use --debug to see if the task is executed. Next, see https://stackoverflow.com/questions/46608832/testing-if-gradle-task-executed to write certain conditionals to verify whether it worked or not. In which codebase are you testing this? would love to assist you in there!

**Comment by commjoen** [comment]
To further answer your question: the gradle task is not necessary; you just need to create a release with version with hte right proguard instructions. See https://stackoverflow.com/questions/2446248/how-to-remove-all-debug-logging-calls-before-publishing-app-to-google-play its accepted answer for more details.

**Comment by sushi2k** [comment]
True, we were actually describing this already anyway in this chapter with  ProGuard. 

I removed the gradle task now in the PR https://github.com/OWASP/owasp-mstg/pull/1081

**Comment by commjoen** [comment]
Fixed :)
