### ISSUE TITLE
iOS Basic Testing: Add howto and examples for using Objection

### ISSUE THREAD

**Issue by b-mueller** [OWASP/owasp-mstg#806]
The paragraph mentioning Objection is very barebones. Add the steps for repackaging and some usage examples.

https://github.com/OWASP/owasp-mstg/blob/master/Document/0x06b-Basic-Security-Testing.md#automated-re-packaging-with-objection

**Comment by sushi2k** [comment]
I was adding this a while back and I didn't wanted to go into detail on this and just link to the objection documentation. The wiki of objection already describes everything very well and is maintained. Otherwise we will run out of sync with the original docs if we copy the steps for repackaging with objection.

**Comment by leonjza** [comment]
I am planning on contributing something for this that should at least give _some_ usage examples on how to use objection on an assessment.

**Comment by godzillahacker** [comment]
-> Thanks to sushi2k for a great workshop: 
Underneath a quick summary. 

Steps to follow when using objection to wrap an ipa file with frida: 
Install objection
https://github.com/sensepost/objection/wiki/Patching-iOS-Applications

Then have xcode installed with a valid developer certificate. 

Create new ios app in xcode 
add device to code base
run app code
get developer signature: 
wrap app with frida: security find-identity -p codesigning -v
objection patchipa --source Snapchat-cracked.ipa --codesign-signature <signature>
first unzip the resigned app
install patched app on iphone: ios-deploy --bundle Payload/[Snapchat.app]  -W -d

on a new terminal 
> objection explore 
> objection env
> ios sslpinning disable
> ios plist cat

**Comment by commjoen** [comment]
Any updates on this? There is a writeup now, but what else should be done?

**Comment by leonjza** [comment]
Apologies, this one fell through the cracks for me, moving it up the stack for me.

**Comment by commjoen** [comment]
Any news on this @leonjza ?

**Comment by commjoen** [comment]
Another nice item: Add stuff to it, like https://medium.com/0xcc/xcode-instruments-for-ios-reversing-and-abuse-dd73d72d87e2 (test it first before the write down ofcourse ;-))

**Comment by commjoen** [comment]
Added @cpholguera : maybe you can work together at it?

**Comment by sushi2k** [comment]
I added objection already a while back to the reverse engineering chapter of iOS. 
https://github.com/OWASP/owasp-mstg/blob/master/Document/0x06c-Reverse-Engineering-and-Tampering.md#automated-repackaging-with-objection 
As the documentation of objection is quite detailed and up-to-date I would suggest to reference to the Github Wiki of objection instead. Otherwise we duplicate documentation that will become out of-sync with the objection Github Wiki. 
At the moment objection is referenced in testing data storage for iOS and also Touch ID. I just added it also for disabling SSL Pinning on iOS https://github.com/OWASP/owasp-mstg/pull/1122. 

Any other topics we should cover from objection @leonjza  and @cpholguera?

**Comment by leonjza** [comment]
I think mention of some more features such as the easy return value modifier's for [iOS](https://github.com/sensepost/objection/blob/master/objection/console/helpfiles/ios.hooking.set.return_value.txt) and [Android](https://github.com/sensepost/objection/blob/master/objection/console/helpfiles/android.hooking.set.return_value.txt) (to name one) may also be worth touching on. Cases where one may have an enclosing method implementing some security check (such as root/jb detection or pinning for example) could be bypassed by simply modifying its return.

All in all, the wiki itself is the most up to date, but it would be grand to have example usages in the MSTG. That being said, I have been wrapping up a major release for objection (which will probably be version 2.0) to improve many things as well as add some neat new features. After this, chances are slim that things would change drastically in the future as the recipe used seems to work great so far, meaning usage documentation may remain relatively static too.

Would it be possible to park this ticket until 2.0 lands?

**Comment by sushi2k** [comment]
Thanks for the quick response! Sure, let's park this ticket for now and if there is any way a new version coming then it makes sense waiting for that. 
We wanted to make the 1.2 release (this ticket is part of the 1.2 milestone) during the OWASP Summit in June 2019. Would be great if the description of the new features of objection would also be part of that.

**Comment by cpholguera** [comment]
@sushi2k maybe we can cover this as part of issue #1230 and close this one? The idea is to have such a section on Android and one on iOS, both focusing on the benefits that objection brings to each OS.

**Comment by commjoen** [comment]
CAn now be closed with #1289
