### ISSUE TITLE
iOS Basic Testing: Verify that re-packaging works

### ISSUE THREAD

**Issue by b-mueller** [OWASP/owasp-mstg#812]
The iOS basic testing guide has a section about testing on non-jailbroken devices. I wrote this a while ago based on some work i did on an iOS 8 device. It would be great if someone could try to reproduce the steps and see if this still works, plus point out any errors (or maybe find an easier way to do this altogether).

Edit: The same thing could probably be done easier with [Cydia Impactor](http://www.cydiaimpactor.com). I'm hesitant to recommend it though as it asks for iTunes username/password of the dev account...

**Comment by pmilosev** [comment]
Can you point to the location in document where you describe this ?
I think I read something similar when checking the tools that could do memory dump on a non-jailbroken device, but not sure if I read it from MSTG or some tool documentation.

Btw, I have a script developed many years ago that can do IPA re-signing / packaging (wrapper around codesign). I think there should already be FLOSS solutions out there, otherwise I could try to liberate / publish it (currently it's company property).

**Comment by b-mueller** [comment]
Bit of a late answer but repackaging is discussed [here]( https://github.com/OWASP/owasp-mstg/blob/master/Document/0x06b-Basic-Security-Testing.md#dynamic-analysis-on-non-jailbroken-devices).

**Comment by sushi2k** [comment]
I was reviewing this section already 2 months back and was executing the steps on an iOS app during a pentest engagement. Was working for me on iOS 10. 
I made a few adjustments to this section and also added objection at the end that also does the job for you.
