### ISSUE TITLE
Bypassing SSL pinning with code obfuscation on Android

### ISSUE THREAD

**Issue by bradroid** [OWASP/owasp-mstg#892]
Source: https://github.com/OWASP/owasp-mstg/blob/master/Document/0x05b-Basic-Security_Testing.md

> There are several ways to bypass certificate pinning for a black box test, for example, SSLUnpinning and Android-SSL-TrustKiller. Certificate pinning can be bypassed within seconds, but only if the app uses the API functions that are covered for these tools. If the app is implementing SSL Pinning with a framework or library that those tools don't yet implement, the SSL Pinning must be manually patched and deactivated, which can be time-consuming.

I looked into the SSLUnpinning and Android-SSL-TrustKiller tools, they rely on http://www.cydiasubstrate.com/api/c/MSJavaHookClassLoad/ 

> Certificate pinning can be bypassed within seconds, but only if the app uses the API functions that are covered for these tools.

I wonder if code obfuscation will prevent these tools from working, because Proguard will obfuscate the class and method names these hooks rely on? For example, I'm using OkHttp which is covered by these tools, but I'm not sure if default Proguard configuration will change it's API and render `MSJavaHookClassLoad` and similar hooks useless?

**Comment by TheDauntless** [comment]
I can write some info on circumventing obfuscated OkHTTP code. Does it fit in this chapter, or should it be put somewhere else?

The same paragraph also says:
> See the test case Testing Custom Certificate Stores and Certificate Pinning" for more details."

but I'm unable to find this test case. Should I maybe add what I said above to 0x05j-Testing-Resiliency-Against-Reverse-Engineering.md and link it correctly?

**Comment by commjoen** [comment]
This testcase is 0x5g fro Android. 
It is indeed true that the standard pinning cannot be protected by means of obfuscation, given the libraries used below. For this, additional pinning controls need to be implemented:
- application level public key pinning (E.g. use payload encryption in which you would pin against an application level public key: implementing JWE for instance)
- Bytecode public key validation using your own library (transport level)
- Using protocols like SRP for remote authentication (yet: Trust on first use, is vulnerable on first use)

**Comment by TheDauntless** [comment]
Ok, so there are two issues here then:

1. What can a developer do to *improve* on the default SSL pinning implementations
2. If the developer has applied these techniques, how do you get around this

The first would make sense, and I can write some stuff on top of that. The second is more on "how to attack" vs "how to defend". Do we want that kind of info? Since we do have a section on "circumventing root detection", I think it could be put in there? (ie: Testing RE resiliency)

**Comment by commjoen** [comment]
So, I don't believe in asking developers to do pinning themselves: because writing your own pinning strategies is often hard an error-prone. Therefore, I would say:
- recommend to use default pinning strategies (e.g. X509trustmanagerfactory, okhttppiner, etc.)
- if a developer wants to counter an attacker that has LOCAL control over the device/app, apply anti-anti-pinning (.e.g. anti-reverse-engineering techniques) to further improve the SSL pinning techniques. This is no longer part of the pinning chapter, but should be part of another chapter.

**Comment by commjoen** [comment]
Section 0x06j and 0x05j are here to further detail (anti-anti) reverse-engineering.

**Comment by sushi2k** [comment]
@TheDauntless Was there any action taken for this ticket yet?

**Comment by 51j0** [comment]
@TheDauntless Are we done with this?

**Comment by TheDauntless** [comment]
This issue can be closed (but I don't have those rights)

**Comment by commjoen** [comment]
Closing it. Thanks!
